"""Standalone Template IR compilation and generation-time retrieval."""

from .annotation import (
    PROMPT_VERSION,
    CallableStructuredVLMClient,
    DeterministicAnnotator,
    SemanticAnnotator,
    SlideAnnotationInput,
    SlideAnnotationResponse,
    StructuredVLMClient,
    VLMAnnotator,
)
from .compiler import COMPILER_VERSION, TemplateCompilationError, TemplateCompiler
from .context import ReferenceMatch, SlideNeed, TemplateContextProvider
from .deeppresenter_client import DeepPresenterStructuredVLMClient
from .extractor import (
    EXTRACTOR_VERSION,
    ExtractionResult,
    ExtractedAsset,
    PptxExtractor,
)
from .ids import derive_revision_id, derive_template_id
from .models import (
    SCHEMA_VERSION,
    SUPPORTED_ASPECT_RATIOS,
    Asset,
    AssetIndex,
    AssetRole,
    BoundingBox,
    Canvas,
    CompactSlideContext,
    LayoutFamily,
    LayoutFamilyIndex,
    NormalizedBox,
    PageSemantics,
    Region,
    ReusePolicy,
    Revision,
    Semantic,
    ShapeNode,
    SlideIndexEntry,
    SourceGraph,
    TemplateManifest,
    TemplateRevision,
    Theme,
    ValidationReport,
)
from .rendering import (
    LibreOfficeRenderer,
    NullRenderer,
    RenderedSlide,
    SlideRenderer,
    create_shape_overlay,
    overlay_labels,
)
from .runtime import (
    TaskTemplateContext,
    TemplateContextConflictError,
    TemplateRuntime,
    materialize_context_pack,
)
from .store import (
    LegacyTemplateError,
    TemplateAspectRatioMismatchError,
    TemplateIntegrityError,
    TemplateNotFoundError,
    TemplateRevision as RuntimeTemplateRevision,
    TemplateRevisionNotReadyError,
    TemplateStore,
    TemplateStoreError,
    UnsafeTemplatePathError,
)

__all__ = [
    "EXTRACTOR_VERSION",
    "SCHEMA_VERSION",
    "SUPPORTED_ASPECT_RATIOS",
    "Asset",
    "AssetIndex",
    "AssetRole",
    "BoundingBox",
    "CallableStructuredVLMClient",
    "Canvas",
    "CompactSlideContext",
    "COMPILER_VERSION",
    "DeterministicAnnotator",
    "DeepPresenterStructuredVLMClient",
    "ExtractionResult",
    "ExtractedAsset",
    "LayoutFamily",
    "LayoutFamilyIndex",
    "LegacyTemplateError",
    "LibreOfficeRenderer",
    "NormalizedBox",
    "NullRenderer",
    "PageSemantics",
    "PptxExtractor",
    "PROMPT_VERSION",
    "ReferenceMatch",
    "Region",
    "RenderedSlide",
    "ReusePolicy",
    "Revision",
    "RuntimeTemplateRevision",
    "Semantic",
    "SemanticAnnotator",
    "ShapeNode",
    "SlideAnnotationInput",
    "SlideAnnotationResponse",
    "SlideIndexEntry",
    "SlideNeed",
    "SlideRenderer",
    "SourceGraph",
    "StructuredVLMClient",
    "TemplateCompilationError",
    "TemplateAspectRatioMismatchError",
    "TemplateCompiler",
    "TemplateContextConflictError",
    "TemplateContextProvider",
    "TemplateIntegrityError",
    "TemplateManifest",
    "TemplateNotFoundError",
    "TemplateRevision",
    "TemplateRevisionNotReadyError",
    "TemplateRuntime",
    "TemplateStore",
    "TemplateStoreError",
    "TaskTemplateContext",
    "Theme",
    "UnsafeTemplatePathError",
    "VLMAnnotator",
    "ValidationReport",
    "create_shape_overlay",
    "derive_revision_id",
    "derive_template_id",
    "materialize_context_pack",
    "overlay_labels",
]
